#!/bin/bash

# Note: You should split this file into multiple batch files and run
# as separate jobs on your batch system.
# Otherwise it will take forever.

# Remember to copy data first
# remember to load libraries
# run BLIP on A40 or A100
# run LLAVA on A100
# *** Can run on smaller GPU by decreasing evaluation batchsize with flag --bs <batch_size>

################################### Make LLAVA Captions ####################################
python scripts/make_llava_captions.py --dataset ImageNet     --prompt "What is in this photo?"
python scripts/make_llava_captions.py --dataset Caltech101   --prompt "What is in this photo?"
python scripts/make_llava_captions.py --dataset OxfordPets   --prompt "What type of pet is in this photo?"
python scripts/make_llava_captions.py --dataset StanfordCars --prompt "What type of car is in this photo?"
python scripts/make_llava_captions.py --dataset Flowers102   --prompt "What type of flower is in this photo?"
python scripts/make_llava_captions.py --dataset Food101      --prompt "What type of food is in this photo?"
python scripts/make_llava_captions.py --dataset FGVCAircraft --prompt "What type of aircraft is in this photo?"
python scripts/make_llava_captions.py --dataset SUN397       --prompt "What is in this photo?"
python scripts/make_llava_captions.py --dataset DTD          --prompt "Describe the texture in this photo."
python scripts/make_llava_captions.py --dataset EuroSAT      --prompt "What type of land use is in this satellite photo?"
python scripts/make_llava_captions.py --dataset UCF101       --prompt "What type of action is in this photo?"
python scripts/make_llava_captions.py --dataset ImageNetV2   --prompt "What is in this photo?"
python scripts/make_llava_captions.py --dataset ImageNetSketch --prompt "What is in this photo?"
python scripts/make_llava_captions.py --dataset ImageNetA    --prompt "What is in this photo?"
python scripts/make_llava_captions.py --dataset ImageNetR    --prompt "What is in this photo?"

python scripts/make_llava_captions.py --dataset ImageNet --prompt "What is in this photo? Be specific." --suffix ".specific"
python scripts/make_llava_captions.py --dataset Caltech101 --prompt "What is in this photo? Be specific." --suffix ".specific"
python scripts/make_llava_captions.py --dataset OxfordPets --prompt "What type of pet is in this photo? Be specific." --suffix ".specific"
python scripts/make_llava_captions.py --dataset StanfordCars --prompt "What type of car is in this photo? Be specific." --suffix ".specific"
python scripts/make_llava_captions.py --dataset Flowers102 --prompt "What type of flower is in this photo? Be specific." --suffix ".specific"
python scripts/make_llava_captions.py --dataset Food101 --prompt "What type of food is in this photo? Be specific." --suffix ".specific"
python scripts/make_llava_captions.py --dataset FGVCAircraft --prompt "What type of aircraft is in this photo? Be specific." --suffix ".specific"
python scripts/make_llava_captions.py --dataset SUN397 --prompt "What is in this photo? Be specific." --suffix ".specific"
python scripts/make_llava_captions.py --dataset DTD --prompt "Describe the texture in this photo. Be specific." --suffix ".specific"
python scripts/make_llava_captions.py --dataset EuroSAT --prompt "What type of land use is in this satellite photo? Be specific." --suffix ".specific"
python scripts/make_llava_captions.py --dataset UCF101 --prompt "What type of action is in this photo? Be specific." --suffix ".specific"
python scripts/make_llava_captions.py --dataset ImageNetV2 --prompt "What is in this photo? Be specific." --suffix ".specific"
python scripts/make_llava_captions.py --dataset ImageNetSketch --prompt "What is in this photo? Be specific." --suffix ".specific"
python scripts/make_llava_captions.py --dataset ImageNetA --prompt "What is in this photo? Be specific." --suffix ".specific"
python scripts/make_llava_captions.py --dataset ImageNetR --prompt "What is in this photo? Be specific." --suffix ".specific"

python scripts/make_llava_captions.py --dataset ImageNet --prompt "What is in this photo? Be concise." --suffix ".concise"
python scripts/make_llava_captions.py --dataset Caltech101 --prompt "What is in this photo? Be concise." --suffix ".concise"
python scripts/make_llava_captions.py --dataset OxfordPets --prompt "What type of pet is in this photo? Be concise." --suffix ".concise"
python scripts/make_llava_captions.py --dataset StanfordCars --prompt "What type of car is in this photo? Be concise." --suffix ".concise"
python scripts/make_llava_captions.py --dataset Flowers102 --prompt "What type of flower is in this photo? Be concise." --suffix ".concise"
python scripts/make_llava_captions.py --dataset Food101 --prompt "What type of food is in this photo? Be concise." --suffix ".concise"
python scripts/make_llava_captions.py --dataset FGVCAircraft --prompt "What type of aircraft is in this photo? Be concise." --suffix ".concise"
python scripts/make_llava_captions.py --dataset SUN397 --prompt "What is in this photo? Be concise." --suffix ".concise"
python scripts/make_llava_captions.py --dataset DTD --prompt "Describe the texture in this photo. Be concise." --suffix ".concise"
python scripts/make_llava_captions.py --dataset EuroSAT --prompt "What type of land use is in this satellite photo? Be concise." --suffix ".concise"
python scripts/make_llava_captions.py --dataset UCF101 --prompt "What type of action is in this photo? Be concise." --suffix ".concise"
python scripts/make_llava_captions.py --dataset ImageNetV2 --prompt "What is in this photo? Be concise." --suffix ".concise"
python scripts/make_llava_captions.py --dataset ImageNetSketch --prompt "What is in this photo? Be concise." --suffix ".concise"
python scripts/make_llava_captions.py --dataset ImageNetA --prompt "What is in this photo? Be concise." --suffix ".concise"
python scripts/make_llava_captions.py --dataset ImageNetR --prompt "What is in this photo? Be concise." --suffix ".concise"


# ################################### Make BLIP-2 Captions ####################################
python scripts/make_blip_captions.py --dataset ImageNet     --prompt "Question: What is in this photo? Answer: A photo of "
python scripts/make_blip_captions.py --dataset Caltech101   --prompt "Question: What is in this photo? Answer: A photo of "
python scripts/make_blip_captions.py --dataset OxfordPets   --prompt "Question: What type of pet is in this photo? Answer: A photo of "
python scripts/make_blip_captions.py --dataset StanfordCars --prompt "Question: What type of car is in this photo? Answer: A photo of "
python scripts/make_blip_captions.py --dataset Flowers102   --prompt "Question: What type of flower is in this photo? Answer: A photo of "
python scripts/make_blip_captions.py --dataset Food101      --prompt "Question: What type of food is in this photo? Answer: A photo of "
python scripts/make_blip_captions.py --dataset FGVCAircraft --prompt "Question: What type of aircraft is in this photo? Answer: A photo of "
python scripts/make_blip_captions.py --dataset SUN397       --prompt "Question: What is in this photo? Answer: A photo of "
python scripts/make_blip_captions.py --dataset DTD          --prompt "Question: Describe the texture in this photo. Answer: A photo of "
python scripts/make_blip_captions.py --dataset EuroSAT      --prompt "Question: What type of land use is in this satellite photo? Answer: A photo of "
python scripts/make_blip_captions.py --dataset UCF101       --prompt "Question: What type of action is in this photo? Answer: A photo of "
python scripts/make_blip_captions.py --dataset ImageNetV2   --prompt "Question: What is in this photo? Answer: A photo of "
python scripts/make_blip_captions.py --dataset ImageNetSketch --prompt "Question: What is in this photo? Answer: A photo of "
python scripts/make_blip_captions.py --dataset ImageNetA    --prompt "Question: What is in this photo? Answer: A photo of "
python scripts/make_blip_captions.py --dataset ImageNetR    --prompt "Question: What is in this photo? Answer: A photo of "

python scripts/make_blip_captions.py --dataset ImageNet --prompt "Question: What is in this photo? Be specific. Answer: A photo of " --suffix ".specific"
python scripts/make_blip_captions.py --dataset Caltech101 --prompt "Question: What is in this photo? Be specific. Answer: A photo of " --suffix ".specific"
python scripts/make_blip_captions.py --dataset OxfordPets --prompt "Question: What type of pet is in this photo? Be specific. Answer: A photo of " --suffix ".specific"
python scripts/make_blip_captions.py --dataset StanfordCars --prompt "Question: What type of car is in this photo? Be specific. Answer: A photo of " --suffix ".specific"
python scripts/make_blip_captions.py --dataset Flowers102 --prompt "Question: What type of flower is in this photo? Be specific. Answer: A photo of " --suffix ".specific"
python scripts/make_blip_captions.py --dataset Food101 --prompt "Question: What type of food is in this photo? Be specific. Answer: A photo of " --suffix ".specific"
python scripts/make_blip_captions.py --dataset FGVCAircraft --prompt "Question: What type of aircraft is in this photo? Be specific. Answer: A photo of " --suffix ".specific"
python scripts/make_blip_captions.py --dataset SUN397 --prompt "Question: What is in this photo? Be specific. Answer: A photo of " --suffix ".specific"
python scripts/make_blip_captions.py --dataset DTD --prompt "Question: Describe the texture in this photo. Be specific. Answer: A photo of " --suffix ".specific"
python scripts/make_blip_captions.py --dataset EuroSAT --prompt "Question: What type of land use is in this satellite photo? Be specific. Answer: A photo of " --suffix ".specific"
python scripts/make_blip_captions.py --dataset UCF101 --prompt "Question: What type of action is in this photo? Be specific. Answer: A photo of " --suffix ".specific"
python scripts/make_blip_captions.py --dataset ImageNetV2 --prompt "Question: What is in this photo? Be specific. Answer: A photo of " --suffix ".specific"
python scripts/make_blip_captions.py --dataset ImageNetSketch --prompt "Question: What is in this photo? Be specific. Answer: A photo of " --suffix ".specific"
python scripts/make_blip_captions.py --dataset ImageNetA --prompt "Question: What is in this photo? Be specific. Answer: A photo of " --suffix ".specific"
python scripts/make_blip_captions.py --dataset ImageNetR --prompt "Question: What is in this photo? Be specific. Answer: A photo of " --suffix ".specific"

python scripts/make_blip_captions.py --dataset ImageNet --prompt "Question: What is in this photo? Be concise. Answer: A photo of " --suffix ".concise"
python scripts/make_blip_captions.py --dataset Caltech101 --prompt "Question: What is in this photo? Be concise. Answer: A photo of " --suffix ".concise"
python scripts/make_blip_captions.py --dataset OxfordPets --prompt "Question: What type of pet is in this photo? Be concise. Answer: A photo of " --suffix ".concise"
python scripts/make_blip_captions.py --dataset StanfordCars --prompt "Question: What type of car is in this photo? Be concise. Answer: A photo of " --suffix ".concise"
python scripts/make_blip_captions.py --dataset Flowers102 --prompt "Question: What type of flower is in this photo? Be concise. Answer: A photo of " --suffix ".concise"
python scripts/make_blip_captions.py --dataset Food101 --prompt "Question: What type of food is in this photo? Be concise. Answer: A photo of " --suffix ".concise"
python scripts/make_blip_captions.py --dataset FGVCAircraft --prompt "Question: What type of aircraft is in this photo? Be concise. Answer: A photo of " --suffix ".concise"
python scripts/make_blip_captions.py --dataset SUN397 --prompt "Question: What is in this photo? Be concise. Answer: A photo of " --suffix ".concise"
python scripts/make_blip_captions.py --dataset DTD --prompt "Question: Describe the texture in this photo. Be concise. Answer: A photo of " --suffix ".concise"
python scripts/make_blip_captions.py --dataset EuroSAT --prompt "Question: What type of land use is in this satellite photo? Be concise. Answer: A photo of " --suffix ".concise"
python scripts/make_blip_captions.py --dataset UCF101 --prompt "Question: What type of action is in this photo? Be concise. Answer: A photo of " --suffix ".concise"
python scripts/make_blip_captions.py --dataset ImageNetV2 --prompt "Question: What is in this photo? Be concise. Answer: A photo of " --suffix ".concise"
python scripts/make_blip_captions.py --dataset ImageNetSketch --prompt "Question: What is in this photo? Be concise. Answer: A photo of " --suffix ".concise"
python scripts/make_blip_captions.py --dataset ImageNetA --prompt "Question: What is in this photo? Be concise. Answer: A photo of " --suffix ".concise"
python scripts/make_blip_captions.py --dataset ImageNetR --prompt "Question: What is in this photo? Be concise. Answer: A photo of " --suffix ".concise"

# ################################### Make COCA Captions ####################################
python scripts/make_coca_captions.py --dataset ImageNet     --prompt "a " --suffix ".a"
python scripts/make_coca_captions.py --dataset Caltech101   --prompt "a " --suffix ".a"
python scripts/make_coca_captions.py --dataset OxfordPets   --prompt "a " --suffix ".a"
python scripts/make_coca_captions.py --dataset StanfordCars --prompt "a " --suffix ".a"
python scripts/make_coca_captions.py --dataset Flowers102   --prompt "a " --suffix ".a"
python scripts/make_coca_captions.py --dataset Food101      --prompt "a " --suffix ".a"
python scripts/make_coca_captions.py --dataset FGVCAircraft --prompt "a " --suffix ".a"
python scripts/make_coca_captions.py --dataset SUN397       --prompt "a " --suffix ".a"
python scripts/make_coca_captions.py --dataset DTD          --prompt "a " --suffix ".a"
python scripts/make_coca_captions.py --dataset EuroSAT      --prompt "a " --suffix ".a"
python scripts/make_coca_captions.py --dataset UCF101       --prompt "a " --suffix ".a"
python scripts/make_coca_captions.py --dataset ImageNetV2   --prompt "a " --suffix ".a"
python scripts/make_coca_captions.py --dataset ImageNetSketch --prompt "a " --suffix ".a"
python scripts/make_coca_captions.py --dataset ImageNetA    --prompt "a " --suffix ".a"
python scripts/make_coca_captions.py --dataset ImageNetR    --prompt "a " --suffix ".a"

python scripts/make_coca_captions.py --dataset ImageNet --prompt "a photo of " --suffix ".a_photo_of"
python scripts/make_coca_captions.py --dataset Caltech101 --prompt "a photo of " --suffix ".a_photo_of"
python scripts/make_coca_captions.py --dataset OxfordPets --prompt "a photo of " --suffix ".a_photo_of"
python scripts/make_coca_captions.py --dataset StanfordCars  --prompt "a photo of " --suffix ".a_photo_of"
python scripts/make_coca_captions.py --dataset Flowers102 --prompt "a photo of " --suffix ".a_photo_of"
python scripts/make_coca_captions.py --dataset Food101 --prompt "a photo of " --suffix ".a_photo_of"
python scripts/make_coca_captions.py --dataset FGVCAircraft --prompt "a photo of " --suffix ".a_photo_of"
python scripts/make_coca_captions.py --dataset SUN397 --prompt "a photo of " --suffix ".a_photo_of"
python scripts/make_coca_captions.py --dataset DTD --prompt "a photo of " --suffix ".a_photo_of"
python scripts/make_coca_captions.py --dataset EuroSAT  --prompt "a photo of " --suffix ".a_photo_of"
python scripts/make_coca_captions.py --dataset UCF101  --prompt "a photo of " --suffix ".a_photo_of"
python scripts/make_coca_captions.py --dataset ImageNetV2  --prompt "a photo of " --suffix ".a_photo_of"
python scripts/make_coca_captions.py --dataset ImageNetSketch  --prompt "a photo of " --suffix ".a_photo_of"
python scripts/make_coca_captions.py --dataset ImageNetA  --prompt "a photo of " --suffix ".a_photo_of"
python scripts/make_coca_captions.py --dataset ImageNetR  --prompt "a photo of " --suffix ".a_photo_of"

python scripts/make_coca_captions.py --dataset ImageNet  --prompt "a photo containing " --suffix ".a_photo_containing"
python scripts/make_coca_captions.py --dataset Caltech101 --prompt "a photo containing " --suffix ".a_photo_containing"
python scripts/make_coca_captions.py --dataset OxfordPets --prompt "a photo containing " --suffix ".a_photo_containing"
python scripts/make_coca_captions.py --dataset StanfordCars --prompt "a photo containing " --suffix ".a_photo_containing"
python scripts/make_coca_captions.py --dataset Flowers102 --prompt "a photo containing " --suffix ".a_photo_containing"
python scripts/make_coca_captions.py --dataset Food101 --prompt "a photo containing " --suffix ".a_photo_containing"
python scripts/make_coca_captions.py --dataset FGVCAircraft --prompt "a photo containing " --suffix ".a_photo_containing"
python scripts/make_coca_captions.py --dataset SUN397 --prompt "a photo containing " --suffix ".a_photo_containing"
python scripts/make_coca_captions.py --dataset DTD --prompt "a photo containing " --suffix ".a_photo_containing"
python scripts/make_coca_captions.py --dataset EuroSAT --prompt "a photo containing " --suffix ".a_photo_containing"
python scripts/make_coca_captions.py --dataset UCF101 --prompt "a photo containing " --suffix ".a_photo_containing"
python scripts/make_coca_captions.py --dataset ImageNetV2 --prompt "a photo containing " --suffix ".a_photo_containing"
python scripts/make_coca_captions.py --dataset ImageNetSketch --prompt "a photo containing " --suffix ".a_photo_containing"
python scripts/make_coca_captions.py --dataset ImageNetA --prompt "a photo containing " --suffix ".a_photo_containing"
python scripts/make_coca_captions.py --dataset ImageNetR --prompt "a photo containing " --suffix ".a_photo_containing"
